title: Site

fields:
  title:
    label: Title
    type:  text

  author:
    label: Author
    type:  text

  subtitle:
    label: soustitre
    type:  text

  description:
    label: Description
    type:  markdown

  footer:
    label: footer intro
    type:  markdown

  copyright:
    label: Copyright
    type:  markdown
